
name: Alpro
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test install node_modules
        run: npm i
      - name: Check if test npm command works
        run: npm run test
      - name: Check build status
        run: npm run build
      - name: Check start status
        run: npm run start
